version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - transcendence_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - transcendence_network
    depends_on:
      - postgres
    restart: always

  nest:
    image: nestjs_img
    build:
      context: ./back
    container_name: nest_container
    command: npm run start:dev
    restart: always
    ports:
      - "3000:3000"
    networks:
      - transcendence_network
    volumes:
      - nest:/usr/src/app
      - /usr/src/app/node_modules

  react:
    image: reactjs_img
    build:
      context: ./front
    container_name: react_container
    command: npm run dev
    restart: always
    ports:
      - "8000:8000"
    networks:
      - transcendence_network
    volumes:
      - react:/app
      - /usr/src/app/node_modules


volumes:
  postgres:
    driver: local
    name: nest-db
    driver_opts:
      type: none 
      o: bind
      device: ./postgres
  pgadmin:
    driver: local
    name: pgadmin
    driver_opts:
      type: none 
      o: bind
      device: ./pgadmin
  nest:
    driver: local
    name: nest
    driver_opts:
      type: none 
      o: bind
      device: ./back
  react:
    driver: local
    name: react
    driver_opts:
      type: none 
      o: bind
      device: ./front

networks:
  transcendence_network:
    driver: bridge
    name: transcendence_network