version: '3.3'
services:
########################################## POSTGRESQL - DATABASE ##############################
  db:
    image: postgres:latest
    container_name: db_container
    hostname: postgres
    restart: always
    env_file:
      - .env
    networks:
      - transcendence_network
########################################## BACK-END NEST JS ##################################
  back:
    image: nestjs_img
    build:
      context: ./back
    container_name: nest_container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - transcendence_network
    volumes:
      - back:/usr/src/app
########################################## FRONT-END REACT VITE  ############################
  front:
    image: reactjs_img
    build:
      context: ./front
    container_name: react_container
    restart: always
    ports:
      - "8000:8000"
    networks:
      - transcendence_network
    volumes:
      - front:/usr/src/app
########################################### VOLUMES  #########################################
volumes:
  db:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: /home/vallienne/42_Projects/transcendence/postgres
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vallienne/42_Projects/transcendence/back
  front:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: /home/vallienne/42_Projects/transcendence/front
########################################## NETWORK  ########################################
networks:
  transcendence_network:
    driver: bridge
