version: '3.3'

networks:
  transcendence_network:
    driver: bridge

services:
########################################## POSTGRESQL - DATABASE ##############################
  db:
    image: postgres:latest
    container_name: db_container
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - ./postgres:/var/lib/postgresql/users

########################################## BACK-END NEST JS ##################################
  back:
    image: nestjs_img
    build:
      context: ./back
    container_name: nest_container
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - db
########################################## FRONT-END REACT VITE  ############################
  front:
    image: reactjs_img
    build:
      context: ./front
    container_name: react_container
    restart: always
    ports:
      - "8000:8000"
    networks:
      - transcendence_network
    volumes:
      - ./front:/usr/src/app
########################################## PGADMIN  ########################################
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   env_file:
  #     - .env
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - transcendence_network
  #   depends_on:
  #     - db
  #   restart: always
########################################### VOLUMES  #########################################
volumes:
  db:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: ./postgres
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./back
  front:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: ./front
  # pgadmin:
  #   driver: local
  #   driver_opts:
  #     type: none 
  #     o: bind
  #     device: /home/vallienne/42_Projects/transcendence/pgadmin
########################################## NETWORK  ########################################