version: '3.3'
services:
########################################## POSTGRESQL - DATABASE ##############################
  db:
    image: postgres:latest
    container_name: db_container
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - database:/var/lib/postgresql/data

########################################## BACK-END NEST JS ##################################
  back:
    image: nestjs_img
    build:
      context: ./back
    container_name: nest_container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - transcendence_network
    env_file:
      - .env
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - db
########################################## FRONT-END REACT VITE  ############################
  front:
    image: reactjs_img
    build:
      context: ./front
    container_name: react_container
    restart: always
    ports:
      - "8000:8000"
    networks:
      - transcendence_network
    env_file:
      - .env
    volumes:
      - ./front:/usr/src/app
########################################### VOLUMES  #########################################
volumes:
  database:
########################################## NETWORK  ########################################
networks:
  transcendence_network:
    driver: bridge